spring.application.name=my-best-raksha

spring.datasource.url=jdbc:mysql://localhost:3306/mbr
spring.datasource.username=root
spring.datasource.password=uday@6153

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}